Inital commit of azure function
lbs-training-and/c-sharp-dotnet-training pull request #11
Opened 2024-07-22 18:38 UTC by MathewBeldon

Initial PR

2024-07-25 13:20 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/AzureFunction.Challenge.Persistence/DatabaseInitialiser.cs
> +            _context.Database.EnsureCreated();
https://github.com/stephen-atkinson/recipes-api-base-build/blob/main/Recipes.Core/Application/Extensions/HostExtensions.cs

2024-07-25 13:20 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/AzureFunction.Challenge.Core/Services/ProductService.cs
> +        public async Task<IEnumerable<ProductDto>> GetProductsAsync()
IReadOnlyCollection call ToArray on Select

2024-07-25 13:20 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/AzureFunction.Challenge.Core/Interfaces/IOrderRepository.cs
> +﻿using AzureFunction.Challenge.Core.Models;
RM repository

2024-07-25 13:28 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/README.MD
> +
Add how to run the function

2024-07-25 13:28 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/AzureFunction.Challenge.Core/Models/Order.cs
> +        public string DeliveryAddress { get; set; }
Create address object

2024-07-25 13:29 UTC, MathewBeldon commented on Best Practices/Challenges/AzureFunction/AzureFunction.Challenge.Core/Models/Order.cs
> +        public string DeliveryAddress { get; set; }
Owned types

2024-07-28 15:47 UTC, stephen-atkinson commented
issue (blocking): Need to move this out of the Best Practices folder

2024-08-13 16:14 UTC, stephen-atkinson requested changes

2024-08-13 16:14 UTC, stephen-atkinson commented on Azure Functions/Challenges/AzureFunction.Challenge/Core/Services/OrderService.cs
> +                DeliveryTime = GetDeliveryTime()
Need to persist DeliveryTime
Add new migration for single column
Save to DB
Return as part of the GetOrder endpoint

2024-08-15 14:28 UTC, stephen-atkinson approved these changes

2024-08-15 14:31 UTC, merged